id: IdForTheJudge
key: "GENERATE_KEY"
problem_storage_root:
  - /app/problems
runtime:
  as_x64: /usr/bin/x86_64-linux-gnu-as
  as_x86: /usr/bin/as
  awk: /usr/bin/mawk
  cat: /bin/cat
  g++: /usr/bin/g++
  g++11: /usr/bin/g++
  g++14: /usr/bin/g++
  g++17: /usr/bin/g++
  gcc: /usr/bin/gcc
  gcc11: /usr/bin/gcc
  go: /usr/local/go/bin/go
  java8: /usr/lib/jvm/java-8-openjdk-amd64/bin/java
  javac8: /usr/lib/jvm/java-8-openjdk-amd64/bin/javac
  kotlinc: /root/.sdkman/candidates/kotlin/current/bin/kotlinc
  kotlin_vm: /usr/bin/java
  ld_x64: /usr/bin/x86_64-linux-gnu-ld
  ld_x86: /usr/bin/ld
  mono: /usr/bin/mono
  mono-csc: /usr/bin/mono-csc
  perl: /usr/bin/perl
  php: /usr/bin/php
  python: /usr/local/bin/python2.7
  python3: /usr/bin/python3.5
  ruby2: /usr/bin/ruby
  sed: /bin/sed
  tclsh: /usr/bin/tclsh
  v8dmoj: /usr/bin/v8dmoj
